# Generated by Django 5.2.4 on 2025-07-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sending', models.DateTimeField(auto_now_add=True)),
                ('last_sending', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Completed', 'Завершена'), ('Created', 'Создана'), ('Launched', 'Запущена')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AttemptToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Successfully', 'Успешно'), ('Not successful', 'Не успешно')], max_length=20)),
                ('response', models.TextField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distribution')),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='recipients',
            field=models.ManyToManyField(to='distribution.mailingrecipient'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.message'),
        ),
    ]
