# Generated by Django 5.2.4 on 2025-08-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_distribution_owner_mailingrecipient_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'permissions': [('stop_distribution', 'Can stop distribution'), ('start_distribution', 'Can start distribution')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('Completed', 'Завершена'), ('Created', 'Создана'), ('Launched', 'Запущена')], default='Created', max_length=20),
        ),
    ]
