# Generated by Django 5.2.4 on 2025-08-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_distribution_options_alter_distribution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempttosend',
            options={'permissions': [('view_reports', 'Can view reports')], 'verbose_name': 'отчет', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'permissions': [('stop_distribution', 'Can stop distribution'), ('start_distribution', 'Can start distribution'), ('block_user', 'Can block user'), ('view_user', 'Can view user')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
